package(default_visibility = ["//keyremaplinux:internal"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

cc_library(
    name = "logging",
    hdrs = [
        "logging.h",
    ],
    srcs = [
         "logging.cc"
    ]
)
